name: Rapport d'utilisation GitHub

on:
  workflow_dispatch:
  push:             
    branches:
      - main
      - develop

jobs:
  usage-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installation des dépendances
        run: pip install requests

      - name: Exécution du rapport
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
          REPO: ${{ github.repository }}
        run: python main.py
